export const otherContacts = [
  {
    lastName: 'KIMBUR',
    firstName: 'ARENENG',
    contactType: 'O',
    contactTypeDescription: 'Official',
    relationship: 'PROB',
    relationshipDescription: 'Probation Officer',
    emergencyContact: false,
    nextOfKin: false,
    relationshipId: 6865390,
    personId: 111,
    activeFlag: true,
    approvedVisitorFlag: false,
    canBeContactedFlag: false,
    awareOfChargesFlag: false,
    contactRootOffenderId: 0,
    bookingId: 123,
  },
  {
    lastName: 'LYDYLE',
    firstName: 'URIUALCHE',
    contactType: 'O',
    contactTypeDescription: 'Official',
    relationship: 'CA',
    relationshipDescription: 'Case Administrator',
    emergencyContact: false,
    nextOfKin: false,
    relationshipId: 7350143,
    personId: 222,
    activeFlag: true,
    approvedVisitorFlag: false,
    canBeContactedFlag: false,
    awareOfChargesFlag: false,
    contactRootOffenderId: 0,
    bookingId: 123,
  },
  {
    lastName: 'SMITH',
    firstName: 'TREVOR',
    contactType: 'O',
    contactTypeDescription: 'Official',
    relationship: 'CA',
    relationshipDescription: 'Case Administrator',
    emergencyContact: false,
    nextOfKin: false,
    relationshipId: 7350143,
    personId: 222,
    activeFlag: true,
    approvedVisitorFlag: false,
    canBeContactedFlag: false,
    awareOfChargesFlag: false,
    contactRootOffenderId: 0,
    bookingId: 123,
  },
  {
    lastName: 'JONES',
    firstName: 'ANNE',
    contactType: 'O',
    contactTypeDescription: 'Official',
    relationship: 'OFS',
    relationshipDescription: 'Offender Supervisor',
    emergencyContact: false,
    nextOfKin: false,
    relationshipId: 7350143,
    personId: 222,
    activeFlag: true,
    approvedVisitorFlag: false,
    canBeContactedFlag: false,
    awareOfChargesFlag: false,
    contactRootOffenderId: 0,
    bookingId: 123,
  },
  {
    lastName: 'JONES',
    firstName: 'ANNE',
    contactType: 'O',
    contactTypeDescription: 'Official',
    relationship: 'COM',
    relationshipDescription: 'Community Offender Manager',
    emergencyContact: false,
    nextOfKin: false,
    relationshipId: 7350143,
    personId: 222,
    activeFlag: true,
    approvedVisitorFlag: false,
    canBeContactedFlag: false,
    awareOfChargesFlag: false,
    contactRootOffenderId: 0,
    bookingId: 123,
  },
]

export const businessPrimary = {
  addressType: 'Business',
  flat: '222',
  locality: 'Test locality',
  premise: '999',
  street: 'Business street',
  town: 'London',
  postalCode: 'W1 ABC',
  county: 'London',
  country: 'England',
  comment: null,
  primary: true,
  noFixedAddress: false,
  startDate: '2020-05-01',
  endDate: null,
  phones: [],
  addressUsages: [],
}

export const businessNonPrimary = {
  addressType: 'Business',
  flat: '222',
  locality: 'New locality',
  premise: '000',
  street: 'Business street',
  town: 'Manchester',
  postalCode: 'W2 DEF',
  county: 'Greater Manchester',
  country: 'England',
  comment: null,
  primary: false,
  noFixedAddress: false,
  startDate: '2020-05-01',
  endDate: null,
  phones: [],
  addressUsages: [],
}
