version: '3'
services:
  web:
    build:
      context: .
      args:
        BUILD_NUMBER: dev
        GIT_REF: dev
    ports:
      - '3002:3002'
    depends_on:
      - oauth
      - elite2
      - whereaboutsapi
      - redis
    environment:
      - UPDATE_ATTENDANCE_PRISONS='HLI,MDI,LEI'
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3002
  oauth:
    image: quay.io/hmpps/hmpps-auth:latest
    container_name: oauth_psh
    ports:
      - '9090:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/auth/health']
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  elite2:
    image: quay.io/hmpps/prison-api:latest
    container_name: elite2_psf
    depends_on:
      - oauth
    ports:
      - '8080:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb

  whereaboutsapi:
    image: 'mojdigitalstudio/whereabouts-api:latest'
    container_name: whereaboutsapi
    depends_on:
      - oauth
    ports:
      - '8082:8082'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev,noqueue

  redis:
    image: redis
    ports:
      - 6379:6379
