export const SET_CONFIG = 'SET_CONFIG';

export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SWITCH_AGENCY = 'SWITCH_AGENCY';
export const SET_TERMS_VISIBILITY = 'SET_TERMS_VISIBILITY';

export const SET_ERROR = 'SET_ERROR';
export const RESET_ERROR = 'RESET_ERROR';
export const SET_MESSAGE = 'SET_MESSAGE';
export const SET_LOADED = 'SET_LOADED';

export const SET_VALIDATION_ERROR = 'SET_VALIDATION_ERROR';
export const RESET_VALIDATION_ERRORS = 'RESET_VALIDATION_ERRORS';

export const SET_SEARCH_LOCATION = 'SET_SEARCH_LOCATION';
export const SET_SEARCH_ACTIVITY = 'SET_SEARCH_ACTIVITY';
export const SET_SEARCH_ACTIVITIES = 'SET_SEARCH_ACTIVITIES';
export const SET_SEARCH_LOCATIONS = 'SET_SEARCH_LOCATIONS';
export const SET_SEARCH_DATE = 'SET_SEARCH_DATE';
export const SET_SEARCH_PERIOD = 'SET_SEARCH_PERIOD';
export const SET_HOUSEBLOCK_DATA = 'SET_HOUSEBLOCK_DATA';
export const SET_ORDER_FIELD = 'SET_ORDER_FIELD';
export const SET_ORDER = 'SET_ORDER';
export const SET_ACTIVITY_DATA = 'SET_ACTIVITY_DATA';

export const SET_SHOW_MODAL = 'SET_SHOW_MODAL';
