const test = [
  {
    visitors: [{ personId: 4729491, lastName: 'BLOB', firstName: 'BLOBY', leadVisitor: true, relationship: 'Brother' }],
    visitDetails: {
      eventStatus: 'COMP',
      eventStatusDescription: 'Completed',
      visitType: 'SCON',
      visitTypeDescription: 'Social Contact',
      leadVisitor: 'BLOBY BLOB',
      relationship: 'BRO',
      relationshipDescription: 'Brother',
      startTime: '2020-08-21T09:00:00',
      endTime: '2020-08-21T11:45:00',
      location: 'OFFICIAL VISITS',
      eventOutcome: 'ATT',
      eventOutcomeDescription: 'Attended',
    },
  },
  {
    visitors: [
      {
        personId: 4729490,
        lastName: 'BULL',
        firstName: 'GIVEN NAME1',
        dateOfBirth: '2008-01-01',
        leadVisitor: true,
        relationship: 'Grandson',
      },
    ],
    visitDetails: {
      eventStatus: 'SCH',
      eventStatusDescription: 'Scheduled (Approved)',
      visitType: 'SCON',
      visitTypeDescription: 'Social Contact',
      leadVisitor: 'GIVEN NAME1 BULL',
      relationship: 'GSON',
      relationshipDescription: 'Grandson',
      startTime: '2020-08-01T13:30:00',
      endTime: '2020-08-01T16:00:00',
      location: 'CLOSED VISITS',
      eventOutcome: 'ABS',
      eventOutcomeDescription: 'Absence',
    },
  },
  {
    visitors: [{ personId: 4729491, lastName: 'BLOB', firstName: 'BLOBY', leadVisitor: true, relationship: 'Brother' }],
    visitDetails: {
      eventStatus: 'SCH',
      eventStatusDescription: 'Scheduled (Approved)',
      visitType: 'SCON',
      visitTypeDescription: 'Social Contact',
      leadVisitor: 'BLOBY BLOB',
      relationship: 'BRO',
      relationshipDescription: 'Brother',
      startTime: '2020-07-22T13:30:00',
      endTime: '2020-07-22T16:00:00',
      location: 'SOCIAL VISITS',
      eventOutcome: 'ATT',
      eventOutcomeDescription: 'Attended',
    },
  },
  {
    visitors: [
      {
        personId: 1674445,
        lastName: 'VICTETRIS',
        firstName: 'ALVRULEMEKA',
        leadVisitor: false,
        relationship: 'Other - Social',
      },
      { personId: 4729491, lastName: 'BLOB', firstName: 'BLOBY', leadVisitor: true, relationship: 'Brother' },
      {
        personId: 4729490,
        lastName: 'BULL',
        firstName: 'GIVEN NAME1',
        dateOfBirth: '2008-01-01',
        leadVisitor: true,
        relationship: 'Grandson',
      },
      {
        personId: 4729489,
        lastName: 'BULL',
        firstName: 'DOM',
        dateOfBirth: '1969-04-21',
        leadVisitor: false,
        relationship: 'Case Administrator',
      },
      {
        personId: 4729489,
        lastName: 'BULL',
        firstName: 'DOM',
        dateOfBirth: '1969-04-21',
        leadVisitor: false,
        relationship: 'Case Administrator',
      },
    ],
    visitDetails: {
      eventStatus: 'SCH',
      eventStatusDescription: 'Scheduled (Approved)',
      visitType: 'SCON',
      visitTypeDescription: 'Social Contact',
      leadVisitor: 'GIVEN NAME1 BULL',
      relationship: 'GSON',
      relationshipDescription: 'Grandson',
      startTime: '2020-07-22T09:00:00',
      endTime: '2020-07-22T11:45:00',
      location: 'OFFICIAL VISITS',
      eventOutcome: 'ABS',
      eventOutcomeDescription: 'Absence',
    },
  },
  {
    visitors: [
      {
        personId: 1674445,
        lastName: 'VICTETRIS',
        firstName: 'ALVRULEMEKA',
        leadVisitor: false,
        relationship: 'Other - Social',
      },
      { personId: 4729491, lastName: 'BLOB', firstName: 'BLOBY', leadVisitor: true, relationship: 'Brother' },
      {
        personId: 4729490,
        lastName: 'BULL',
        firstName: 'GIVEN NAME1',
        dateOfBirth: '2008-01-01',
        leadVisitor: true,
        relationship: 'Grandson',
      },
      {
        personId: 4729489,
        lastName: 'BULL',
        firstName: 'DOM',
        dateOfBirth: '1969-04-21',
        leadVisitor: false,
        relationship: 'Case Administrator',
      },
      {
        personId: 4729489,
        lastName: 'BULL',
        firstName: 'DOM',
        dateOfBirth: '1969-04-21',
        leadVisitor: false,
        relationship: 'Case Administrator',
      },
    ],
    visitDetails: {
      eventStatus: 'SCH',
      eventStatusDescription: 'Scheduled (Approved)',
      visitType: 'SCON',
      visitTypeDescription: 'Social Contact',
      leadVisitor: 'DOM BULL',
      relationship: 'CA',
      relationshipDescription: 'Case Administrator',
      startTime: '2020-07-15T13:30:00',
      endTime: '2020-07-15T16:00:00',
      location: 'SOCIAL VISITS',
      eventOutcome: 'ATT',
      eventOutcomeDescription: 'Attended',
    },
  },
  {
    visitors: [
      {
        personId: 1674445,
        lastName: 'VICTETRIS',
        firstName: 'ALVRULEMEKA',
        leadVisitor: false,
        relationship: 'Other - Social',
      },
      { personId: 4729491, lastName: 'BLOB', firstName: 'BLOBY', leadVisitor: true, relationship: 'Brother' },
      {
        personId: 4729490,
        lastName: 'BULL',
        firstName: 'GIVEN NAME1',
        dateOfBirth: '2008-01-01',
        leadVisitor: true,
        relationship: 'Grandson',
      },
      {
        personId: 4729489,
        lastName: 'BULL',
        firstName: 'DOM',
        dateOfBirth: '1969-04-21',
        leadVisitor: false,
        relationship: 'Case Administrator',
      },
      {
        personId: 4729489,
        lastName: 'BULL',
        firstName: 'DOM',
        dateOfBirth: '1969-04-21',
        leadVisitor: false,
        relationship: 'Case Administrator',
      },
    ],
    visitDetails: {
      eventStatus: 'SCH',
      eventStatusDescription: 'Scheduled (Approved)',
      visitType: 'SCON',
      visitTypeDescription: 'Social Contact',
      leadVisitor: 'DOM BULL',
      relationship: 'CA',
      relationshipDescription: 'Case Administrator',
      startTime: '2020-07-15T13:30:00',
      endTime: '2020-07-15T16:00:00',
      location: 'SOCIAL VISITS',
      eventOutcome: 'ATT',
      eventOutcomeDescription: 'Attended',
    },
  },
  {
    visitors: [
      {
        personId: 1674445,
        lastName: 'VICTETRIS',
        firstName: 'ALVRULEMEKA',
        leadVisitor: false,
        relationship: 'Other - Social',
      },
      { personId: 4729491, lastName: 'BLOB', firstName: 'BLOBY', leadVisitor: true, relationship: 'Brother' },
      {
        personId: 4729490,
        lastName: 'BULL',
        firstName: 'GIVEN NAME1',
        dateOfBirth: '2008-01-01',
        leadVisitor: true,
        relationship: 'Grandson',
      },
      {
        personId: 4729489,
        lastName: 'BULL',
        firstName: 'DOM',
        dateOfBirth: '1969-04-21',
        leadVisitor: false,
        relationship: 'Case Administrator',
      },
      {
        personId: 4729489,
        lastName: 'BULL',
        firstName: 'DOM',
        dateOfBirth: '1969-04-21',
        leadVisitor: false,
        relationship: 'Case Administrator',
      },
    ],
    visitDetails: {
      eventStatus: 'SCH',
      eventStatusDescription: 'Scheduled (Approved)',
      visitType: 'SCON',
      visitTypeDescription: 'Social Contact',
      leadVisitor: 'ALVRULEMEKA VICTETRIS',
      relationship: 'OTHER',
      relationshipDescription: 'Other - Social',
      startTime: '2020-07-14T09:00:00',
      endTime: '2020-07-14T11:45:00',
      location: 'OFFICIAL VISITS',
      eventOutcome: 'ATT',
      eventOutcomeDescription: 'Attended',
    },
  },
  {
    visitors: [{ personId: 4729491, lastName: 'BLOB', firstName: 'BLOBY', leadVisitor: true, relationship: 'Brother' }],
    visitDetails: {
      eventStatus: 'CANC',
      eventStatusDescription: 'Cancelled',
      visitType: 'SCON',
      visitTypeDescription: 'Social Contact',
      leadVisitor: 'BLOBY BLOB',
      relationship: 'BRO',
      relationshipDescription: 'Brother',
      startTime: '2020-07-07T09:00:00',
      endTime: '2020-07-07T11:45:00',
      location: 'OFFICIAL VISITS',
      eventOutcome: 'ATT',
      eventOutcomeDescription: 'Attended',
      cancellationReason: 'ADMIN',
      cancelReasonDescription: 'Administrative Cancellation',
    },
  },
  {
    visitors: [
      {
        personId: 4729490,
        lastName: 'BULL',
        firstName: 'GIVEN NAME1',
        dateOfBirth: '2008-01-01',
        leadVisitor: true,
        relationship: 'Grandson',
      },
    ],
    visitDetails: {
      eventStatus: 'CANC',
      eventStatusDescription: 'Cancelled',
      visitType: 'SCON',
      visitTypeDescription: 'Social Contact',
      leadVisitor: 'GIVEN NAME1 BULL',
      relationship: 'GSON',
      relationshipDescription: 'Grandson',
      startTime: '2020-07-01T09:00:00',
      endTime: '2020-07-01T11:45:00',
      location: 'OFFICIAL VISITS',
      eventOutcome: 'ATT',
      eventOutcomeDescription: 'Attended',
      cancellationReason: 'ADMIN',
      cancelReasonDescription: 'Administrative Cancellation',
    },
  },
  {
    visitors: [
      {
        personId: 579266,
        lastName: 'CASSORIA',
        firstName: 'YRUDYPETER',
        dateOfBirth: '1980-07-20',
        leadVisitor: true,
        relationship: 'Probation Officer',
      },
    ],
    visitDetails: {
      eventStatus: 'COMP',
      eventStatusDescription: 'Completed',
      visitType: 'OFFI',
      visitTypeDescription: 'Official Visit',
      leadVisitor: 'YRUDYPETER CASSORIA',
      relationship: 'PROB',
      relationshipDescription: 'Probation Officer',
      startTime: '2020-06-25T13:30:00',
      endTime: '2020-06-25T16:00:00',
      location: 'CLOSED VISITS',
      eventOutcome: 'ATT',
      eventOutcomeDescription: 'Attended',
    },
  },
  {
    visitors: [
      {
        personId: 579266,
        lastName: 'CASSORIA',
        firstName: 'YRUDYPETER',
        dateOfBirth: '1980-07-20',
        leadVisitor: true,
        relationship: 'Probation Officer',
      },
    ],
    visitDetails: {
      eventStatus: 'EXP',
      eventStatusDescription: 'Expired',
      visitType: 'SCON',
      visitTypeDescription: 'Social Contact',
      leadVisitor: 'YRUDYPETER CASSORIA',
      relationship: 'PROB',
      relationshipDescription: 'Probation Officer',
      startTime: '2020-04-17T13:30:00',
      endTime: '2020-04-17T16:00:00',
      location: 'OFFICIAL VISITS',
      eventOutcome: 'ATT',
      eventOutcomeDescription: 'Attended',
    },
  },
  {
    visitors: [
      {
        personId: 579266,
        lastName: 'CASSORIA',
        firstName: 'YRUDYPETER',
        dateOfBirth: '1980-07-20',
        leadVisitor: true,
        relationship: 'Probation Officer',
      },
    ],
    visitDetails: {
      eventStatus: 'EXP',
      eventStatusDescription: 'Expired',
      visitType: 'OFFI',
      visitTypeDescription: 'Official Visit',
      leadVisitor: 'YRUDYPETER CASSORIA',
      relationship: 'PROB',
      relationshipDescription: 'Probation Officer',
      startTime: '2018-08-08T13:30:00',
      endTime: '2018-08-08T16:00:00',
      location: 'CLOSED VISITS',
      eventOutcome: 'ATT',
      eventOutcomeDescription: 'Attended',
    },
  },
]

const visitsWithVisitors = {
  content: [[Object], [Object], [Object], [Object], [Object]],
  pageable: {
    sort: [Object],
    offset: 0,
    pageNumber: 0,
    pageSize: 5,
    paged: true,
    unpaged: false,
  },
  totalPages: 3,
  totalElements: 12,
  last: false,
  sort: { unsorted: true, sorted: false, empty: true },
  first: true,
  number: 0,
  size: 5,
  numberOfElements: 5,
  empty: false,
}