#!/usr/bin/env node

/* eslint-disable no-console */

const fs = require('fs');
const crypto = require('crypto');
const path = require('path');

const { recordBuildInfoTo } = require('./build-info');

const target = path.resolve(__dirname, '../build-info.json');

const getEnvironmentVariable = (name) => {
  if (process.env[name]) {
    return process.env[name];
  }
  throw new Error(`Missing env var ${name}`);
};

const buildInfo = {
  buildNumber: getEnvironmentVariable('BUILD_NUMBER'),
  gitRef: getEnvironmentVariable('GIT_REF'),
  gitDate: getEnvironmentVariable('GIT_DATE')
};

recordBuildInfoTo(target, buildInfo, (error) => {
  if (error) {
    console.log('💔 Failed to record build info');
    return process.exit(1);
  }

  console.log('✨ Successfully recorded build info');
  return process.exit(0);
});
