export default {
  establishmentRoll: '/establishment-roll',
  inToday: '/establishment-roll/in-today',
  iepHistory: '/offenders/:offenderNo/iep-details',
  incentiveLevelDetails: '/offenders/:offenderNo/incentive-level-details',
  incentiveLevelChange: '/offenders/:offenderNo/incentive-level-details/change-incentive-level',
  outToday: '/establishment-roll/out-today',
  inReception: '/establishment-roll/in-reception',
  currentlyOut: '/establishment-roll/:livingUnitId/currently-out',
  enRoute: '/establishment-roll/en-route',
  totalOut: '/establishment-roll/total-currently-out',
  uploadOffenders: '/bulk-appointments/upload-offenders',
  bulkAppointments: '/add-bulk-appointments',
  bulkAppointmentsAddPrisoners: '/add-bulk-appointments/add-prisoners',
  adjudications: '/offenders/:offenderNo/adjudications',
  adjudication: '/offenders/:offenderNo/adjudications/:adjudicationNo',
  prisonersUnaccountedFor: '/manage-prisoner-whereabouts/prisoners-unaccounted-for',
}
